### PR TITLE
Release v0.8.3

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Crashes immediately
https://github.com/Slackadays/Clipboard/issues/168, this needs to be fixed in the application.

I'll revert to 22.08 but it is only supported for another year.

**Comment by bbhtt** [comment]
Ah this wasn't an issue with GCC 13 only, older versions are also affected

**Comment by Slackadays** [comment]
Fixed in https://github.com/Slackadays/Clipboard/commit/ac5982df045034f60e73d0ef81a3fe9ed3225c6b

**Comment by Slackadays** [comment]
You may need to make the Flatpak link to the next commit after the one above instead of the 0.8.3 release because I don't think this is worthy of a 0.8.4 release

**Comment by bbhtt** [comment]
> You may need to make the Flatpak link to the next commit after the one above instead of the 0.8.3 release because I don't think this is worthy of a 0.8.4 release

You bumped the appdata in the same commit, so it'd show up as a new release in Flathub without a release being on Github. That'd be confusing.

I added it as a patch on top of 0.8.3.

It works, thanks

**Comment by bbhtt** [comment]
Also why is there two parallel appdata being maintained? The appdata should live upstream, ideally.

**Pull request merged**
